# Generated by Django 5.2.2 on 2025-06-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_id', models.CharField(max_length=30)),
                ('Employee_name', models.CharField(max_length=100)),
                ('Employee_Emailid', models.EmailField(max_length=254)),
                ('Employee_contact', models.CharField(max_length=20)),
            ],
        ),
    ]
